//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/deathrun_arctic.html
sprites/stmbal1.spr
gfx/env/snowbk.tga
gfx/env/snowdn.tga
gfx/env/snowft.tga
gfx/env/snowlf.tga
gfx/env/snowrt.tga
gfx/env/snowup.tga
overviews/deathrun_arctic.txt
maps/deathrun_arctic.bsp
maps/deathrun_arctic.txt
